CREATE DATABASE IF NOT EXISTS apatolipse;

USE apatolipse;

CREATE TABLE IF NOT EXISTS hospedeiro(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    idade INTEGER NOT NULL,
    sexo VARCHAR(9) NOT NULL,
    peso DECIMAL(8, 2) NOT NULL,
    altura DECIMAL(8, 2) NOT NULL,
    tipoSanguineo VARCHAR(5) NOT NULL,
    esportesPraticados VARCHAR(300),
    jogoPreferido VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS zumbi (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  idHospedeiro INTEGER NOT NULL,
  forca INTEGER NOT NULL,
  velocidade INTEGER NOT NULL,
  inteligencia INTEGER NOT NULL,
  hp INTEGER NOT NULL,
  FOREIGN KEY (idHospedeiro) REFERENCES hospedeiro(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS pato (
	id INTEGER PRIMARY KEY,
    nome VARCHAR(20) NOT NULL UNIQUE,
    hp INTEGER NOT NULL,
    escudoEstaAtivo CHAR(1) NOT NULL
);

CREATE TABLE IF NOT EXISTS habilidades_pato (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    idPato INTEGER NOT NULL,
    codigoHabilidade INTEGER NOT NULL UNIQUE,
    nomeHabilidade VARCHAR(30) NOT NULL UNIQUE,
    dano INTEGER NOT NULL,
    FOREIGN KEY (idPato) REFERENCES pato(id) ON DELETE CASCADE ON UPDATE CASCADE
);
