<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Chose duck - Apatoliptico</title>
  <link rel="stylesheet" href="../css/choose-duck.css?v=<?php echo date('ymdms');?>">
</head>

<body>
  <input type="radio" name="duck" id="duck1" selected>
  <input type="radio" name="duck" id="duck2">
  <input type="radio" name="duck" id="duck3">
  <input type="radio" name="duck" id="duck4">
  
  <h1>Selecione um pato para jogar</h1>
  
  <div class="container">
    <label for="duck1">
      <div class="duck-container">
        <div class="wrapper">
          <div class="banner-image"> </div>
          <p class="duck-name">Joséfa</p>
          <div class="duck-info">
            <p>Habilidades: </p>
            <span class="hability">a</span>
            <span class="hability">b</span>
            <span class="hability">c</span>
            <span class="hability">d</span>
          </div>
        </div>
      </div>
    </label>
    <label for="duck2">
      <div class="duck-container">
        <div class="wrapper">
          <div class="banner-image"> </div>
          <p class="duck-name">Joséfa</p>
          <div class="duck-info">
            <p>Habilidades: </p>
            <span class="hability">a</span>
            <span class="hability">b</span>
            <span class="hability">c</span>
            <span class="hability">d</span>
          </div>
        </div>
      </div>
    </label>
    <label for="duck3">
      <div class="duck-container">
        <div class="wrapper">
          <div class="banner-image"> </div>
          <p class="duck-name">Joséfa</p>
          <div class="duck-info">
            <p>Habilidades: </p>
            <span class="hability">a</span>
            <span class="hability">b</span>
            <span class="hability">c</span>
            <span class="hability">d</span>
          </div>
        </div>
      </div>
    </label>
    <label for="duck4">
      <div class="duck-container">
        <div class="wrapper">
          <div class="banner-image"> </div>
          <p class="duck-name">Joséfa</p>
          <div class="duck-info">
            <p>Habilidades: </p>
            <span class="hability">a</span>
            <span class="hability">b</span>
            <span class="hability">c</span>
            <span class="hability">d</span>
          </div>
        </div>
      </div>
    </label>
  </div>
  
  <button id="play">
    Jogar
  </button>
  <script src="../js/choose-duck.js?v=<?php echo date('ymdms');?>" defer></script>
</body>

</html>