<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Playing - Apatoliptico</title>
    <link rel="stylesheet" href="../css/toast.css?v=<?php echo date('ymdms');?>">
    <link rel="stylesheet" href="../css/game.css?v=<?php echo date('ymdms');?>">
</head>

<body>
    <h1>Batalha - Level <span id="level">1</span></h1>
    <main id="game-container">
        <div class="container">
            <p>Pato: <span id="duck-hp">100 </span> HP</p>
            <img src="../assets/duck-walking.gif" class="img" id="duck-img">
            <div id="habilities-container">
                <button>
                </button>
                <button>
                </button>
                <button>
                </button>
                <button>
                    </button>
            </div>
        </div>
        <div class="container">
            <p>Zumbi: <span id="zombie-hp">100</span> HP</p>
            <img class="img" src="../assets/zombie-game.png">
            Atributos:
            <div id="habilities-container">
                <p>Forca <span id="zombie-strength"></span></p>
                <p>Velocidade <span id="zombie-speed"></span></p>
                <p>Inteligencia <span id="zombie-intelligence"></span></p>
            </div>
        </div>
    </main>

    <div class="fade hide"></div>
    <div class="fadeGreen hide"></div>
    <p id="gameover" class="hide">Game Over!</p>
    <p id="main-menu-link" class="hide">Voltar ao início!</p>    
    
    
    <p id="won" class="hide">A luta continua!</p>
    <p id="next-level" class="hide">Próximo Nível!</p>

    <script src="../js/game.js?v=<?php echo date('ymdms');?>" defer></script>
</body>

</html>