<!DOCTYPE html>
<html lang="pt-BR">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Hospedeiros - Apatoliptico</title>
  <link rel="stylesheet" href="../css/hosters.css?v=<?php echo date('ymdms');?>">
</head>

<body>
  <h1>Hospedeiros Cadastrados</h1>
  <div class="container">
    <div id="template">
      <div class="card-container">
        <div class="wrapper">
          <div class="banner-image"> </div>
          <p class="hoster-name">Joséfa</p>
          <div class="hoster-info">
            <p class="idade">Idade: 80</p>
            <p class="peso">Peso: 80</p>
            <p class="altura">Altura: 1.78</p>
          </div>
        </div>
      </div>
    </div>
    </div>
    <h2 id="no-hosters" class="no-hosters">Ainda não há hospedeiros, <a href="./register-hoster.html">clique aqui</a> para criar o primeiro</h2>
    <script src="../js/hosters.js?v=<?php echo date('ymdms');?>" defer></script>
</body>

</html>