<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Loading Game - Apatoliptico</title>
    <link rel="stylesheet" href="../css/loading.css?v=<?php echo date('ymdms');?>">
</head>
<body>
    <div>
        <img src="../assets/duck-walking.gif">
        <p id="message-loading">Iniciando o jogo ...</p>
    </div>
    <script src="../js/loading.js?v=<?php echo date('ymdms');?>" defer></script>
</body>
</html>