<!DOCTYPE html>
<html lang="pt-Br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Apatoliptico - Menu</title>
    <link rel="stylesheet" href="../css/menu.css?v=<?php echo date('ymdms');?>">
</head>

<body>
    <main>
        <h1>Apatoliptico - Jogar</h1>
        <nav>
            <ul>
                <li>
                    <a href="./choose-duck.phtml" type="button">Iniciar Jogo</a>
                </li>
                <li>
                    <a href="./register-hoster.phtml" type="button">Cadastrar Hospedeiro</a>
                </li>
                <li>
                    <a href="./hosters.phtml" type="button">Ver Hospedeiros</a>
                </li>
                <li>
                    <a href="./about.phtml" type="button">Sobre o Jogo</a>
                </li>
            </ul>
        </nav>
    </main>
</body>

</html>