<!DOCTYPE html>
<html lang="pt-Br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Apatoliptico - Menu</title>
    <link rel="stylesheet" href="../css/toast.css?v=<?php echo date('ymdms');?>">
    <link rel="stylesheet" href="../css/register-hoster.css?v=<?php echo date('ymdms');?>">
    <link rel="shortcut icon" href="../assets/duck-icon.ico?v=<?php echo date('ymdms');?>" type="image/x-icon">
</head>

<body>
    <main>
        <h1>Crie um hospedeiro</h1>
        <form>
            <div class="group">
                <div class="inner-group">
                    <label for="idade">Idade</label>
                    <input type="number" name="idade" id="idade">
                </div>
                <div class="inner-group">
                    <label for="sexo">
                        Selecione o sexo
                    </label>
                    <select id="sexo" name="sexo">
                        <option value="" selected disabled>Selecione ...</option>
                        <option value="Feminino">Feminino</option>
                        <option value="Masculino">Masculino</option>
                    </select>
                </div>

            </div>

            <div class="group">
                <div class="inner-group">
                    <label for="peso">Peso</label>
                    <input type="number" name="peso" id="peso">
                </div>
                <div class="inner-group">
                    <label for="altura">Altura</label>
                    <input type="number" name="altura" id="altura">
                </div>
            </div>

            <div class="group">
                <div class="inner-group">
                    <label for="tipo-sanguineo">Tipo Sanguíneo</label>
                    <select id="tp-sanguineo" name="tipo-sanguineo">
                        <option value="" selected disabled>Selecione ...</option>
                        <option value="A+">A+</option>
                        <option value="A-">A-</option>
                        <option value="B+">B+</option>
                        <option value="B-">B-</option>
                        <option value="AB+">AB+</option>
                        <option value="AB-">AB-</option>
                        <option value="O+">O+</option>
                        <option value="O-">O-</option>
                    </select>
                </div>
                <div class="inner-group">
                    <label for="jogo-preferido">Jogo preferido</label>
                    <select name="jogo-preferido" id="jogo">
                        <option value="">Selecione ...</option>
                        <option value="CrossFiring">CrossFiring</option>
                        <option value="Roblox">Roblox</option>
                        <option value="PUBG">PUBG</option>
                        <option value="Minecraft">Minecraft</option>
                        <option value="Lost Ark">Lost Ark</option>
                        <option value="Counter Strike">Counter Strike</option>
                        <option value="League of Legends">League of Legends</option>
                        <option value="EA FC">EA FC</option>
                    </select>
                </div>
            </div>

            <p>Escolha os esportes praticados</p>

            <div class="checkboxes-container">
                <div class="inner-group">
                    <div>
                        <input type="checkbox" id="futebol" name="futebol" value="futebol" />
                        <label for="futebol"> Futebol</label>
                    </div>
                    <div>
                        <input type="checkbox" id="basquete" name="basquete" value="basquete" />
                        <label for="basquete"> Basquete </label>
                    </div>
                </div>
                <div class="inner-group">
                    <div>
                        <input type="checkbox" id="volei" name="volei" value="volei" />
                        <label for="volei"> Vôlei </label>
                    </div>
                    <div>
                        <input type="checkbox" id="tenis" name="tenis" value="tenis" />
                        <label for="tenis"> Tênis </label>
                    </div>
                </div>
                <div class="inner-group">
                    <div>
                        <input type="checkbox" id="tenis" name="tenis" value="tenis" />
                        <label for="tenis"> Outro </label>
                    </div>
                </div>
            </div>
            
            <button type="submit" id="register-btn">Registrar hospedeiro</button>
            
        </form>
    </main>
    
    <div id="toast-container" class="hide">
        <img id="toast-img" src="">
        <span id="toast-message"></span>
    </div>
    <script type="module" src="../js/register-hoster.js?v=<?php echo date('ymdms');?>" defer></script>
</body>

</html>